services:
  dst:
    build: .
    env_file:
      - .env
    volumes:
      - ./steamcmd:/opt/steamcmd
      - ./dst:/opt/dst
      - ./ugc:/ugc
      - ./data:/data
    ports:
      - 10999:10999/udp
      - 11000:11000/udp
      - 27015:27015/udp
    restart: unless-stopped
