services:
  dst:
    build: .
    env_file:
      - .env
    volumes:
      - ./steam-state:/steam-state
      - ./dst:/opt/dst
      - ./ugc:/ugc
      - ./data:/data
    ports:
      - ${DST_MASTER_HOST_PORT:-11000}:11000/udp
      - ${DST_CAVES_HOST_PORT:-11001}:11001/udp
      - ${DST_STEAM_HOST_PORT:-27018}:27018/udp
      - ${DST_CAVES_STEAM_HOST_PORT:-27019}:27019/udp
    restart: unless-stopped
