[supervisord]
nodaemon=true
user=root

[program:master]
command=%(ENV_DST_SERVER_BINARY)s -cluster %(ENV_DST_CLUSTER_NAME)s -shard Master -conf_dir . -persistent_storage_root %(ENV_DST_DATA_DIR)s -ugc_directory %(ENV_DST_UGC_DIR)s %(ENV_DST_SERVER_EXTRA_ARGS)s
directory=/opt/dst/bin64
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:caves]
command=%(ENV_DST_SERVER_BINARY)s -cluster %(ENV_DST_CLUSTER_NAME)s -shard Caves -conf_dir . -persistent_storage_root %(ENV_DST_DATA_DIR)s -ugc_directory %(ENV_DST_UGC_DIR)s %(ENV_DST_SERVER_EXTRA_ARGS)s
directory=/opt/dst/bin64
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
