[supervisord]
nodaemon=true

[program:master]
command=/opt/dst/bin64/dontstarve_dedicated_server_nullrenderer_x64 -console -cluster Cluster_1 -shard Master -persistent_storage_root /data -ugc_directory /ugc
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:caves]
command=/opt/dst/bin64/dontstarve_dedicated_server_nullrenderer_x64 -console -cluster Cluster_1 -shard Caves -persistent_storage_root /data -ugc_directory /ugc
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
